before_script:
  - mkdir -p $HOME/roms
git:
  depth: false
cache:
  - ccache
  - directories:
    - $HOME/roms/
language: cpp # Needed for ccache
matrix:
  include:
    - os: linux
      services:
        - docker
      before_install:
        - docker pull quay.io/openai/travis-build
      script:
        - >
          docker run
          --env TRAVIS_OS_NAME="$TRAVIS_OS_NAME"
          --env TRAVIS_TAG="$TRAVIS_TAG"
          --env TRAVIS_BRANCH="$TRAVIS_BRANCH"
          --env TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
          --env GOOGLE_APPLICATION_CREDENTIALS_DATA="$GOOGLE_APPLICATION_CREDENTIALS_DATA"
          --volume /home/travis/build/openai/retro:/root/code/retro
          --volume /home/travis/roms:/root/roms
          --volume /home/travis/.ccache:/root/.ccache
          --workdir /root/code/retro
          quay.io/openai/travis-build
          python travis.py
    - os: osx
      osx_image: xcode8
      before_install:
        - curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash miniconda.sh -b
        - export PATH="$HOME/miniconda3/bin:$PATH"
        - hash -r
        - conda install --yes python=3.6.1
        - export PATH=/usr/local/opt/ccache/libexec:$PATH
        - pip install wheel google-cloud pytest pytest-xdist
      script:
        - python travis.py
